services:
  - type: web
    name: sanaderpupdate
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
